v.1.1

diff --git a/tools/deodex b/tools/deodex
--- a/tools/deodex
+++ b/tools/deodex
@@ -1,26 +1,20 @@
 #!/bin/bash
 
+source tools/fn
+
 # Deodex app
 if [[ ! -d app ]] && [[ ! -d framework ]]
 then
-echo "App folder or framework folder not found! Exiting..."
+setterm -bold 
+tput setaf 1 
+echo "App folder and Framework folder not found! Exiting..."
+echo "Press any key"
+tput sgr0
+read
 exit 1
 fi
 echo "Enter number API (Only number)"
-setterm -bold 
-tput setaf 1
-echo "Android 2.1 Eclair (API level 7)
-Android 2.2–2.2.3 Froyo (API level 8) 
-Android 2.3–2.3.2 Gingerbread (API level 9)
-Android 2.3.3–2.3.7 Gingerbread (API level 10)
-Android 3.0 Honeycomb (API level 11)
-Android 3.1 Honeycomb (API level 12)
-Android 3.2 Honeycomb (API level 13)
-Android 4.0–4.0.2 Ice Cream Sandwich (API level 14)
-Android 4.0.3–4.0.4 Ice Cream Sandwich (API level 15)
-Android 4.1 Jelly Bean (API level 16)
-Android 4.2 Jelly Bean (API level 17)"
-tput sgr0
+api_levels
 read -p "API: " api
 if [[ "$api" == "" ]]
 then
@@ -52,7 +46,7 @@ tput setaf 1
 echo "Deodexing"
 tput sgr0
 echo "---------"
-for odexfile in $odexlist
+for odexfile in ${odexlist[@]}
 do
 java -Xmx512m -jar baksmali.jar -a $api -d ../framework -x $odexfile.odex -o $odexfile
 java -Xmx512m -jar smali.jar -a $api $odexfile -o classes.dex
@@ -71,20 +65,21 @@ echo "Found $odexnew Odex Files and $apknew APK Files"
 odexfr=`find framework | grep -c ".odex"`
 jar=`find framework | grep -c ".jar"`
 setterm -bold 
-tput setaf 1 
-echo "Found $odex Odex Files and $jar JAR Files"
+tput setaf 1
+echo "---------"
+echo "Found $odex Odex Files and $jar JAR Files in framework folder"
 tput sgr0
 if
 [[ "$odexfr" == "0" ]]
 then
 echo ".odex files not found! Exiting..."
-exit 0
+exit 1
 fi
 if
 [[ "jar" == "0" ]]
 then
-echo ".apk files not found! Exiting..."
-exit 0
+echo ".jar files not found! Exiting..."
+exit 1
 fi
 cp tools/baksmali.jar tools/smali.jar framework
 cd framework
@@ -92,7 +87,6 @@ odexfrlist=`find *.odex | sed s/.odex//`
 setterm -bold 
 tput setaf 1 
 echo "Deodexing in framework folder"
-echo ""
 tput sgr0
 echo "---------"
 for odexfrfile in $odexfrlist
@@ -105,4 +99,4 @@ echo "$odexfrfile Deodexed"
 done
 rm baksmali.jar smali.jar
 cd ..
-tools/done
+all_done
